config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
	get '/about', to: 'static_pages#about'

	#sessions/login
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	

	#users 
	resources :users, only: [:index]  

	#posts 
	resources :posts, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save :remember

	validates :name, presence: true, length: { maximum: 50 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	
	has_secure_password

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(string)
		Digest::SHA1.hexdigest(string.to_s)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(:remember_token)) if remember_digest.nil?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create]

	def new
		@user = User.find_by(remember_digest: User.digest(cookies.permanent[:remember_token]))
	end

	def create
		@post = Post.new(post_params)
		@post.author_id = @current_user.id

		if @post.save
			flash[:success] = "Post successfully made!"
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def index
		@posts = Post.all
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :author_id)
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	
	def create
		@user = User.find_by(email: params[:session][:email].downcase)

		if @user && @user.authenticate(params[:session][:password])
			log_in @user
			params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
			message = "Successful Login!"
			flash[:success_login] = message
      redirect_to root_url
     else
     	message = "Sorry, that user/password combination must be incorrect ¯\\_(ツ)_/¯ "
     	flash[:warning] = message
      redirect_to root_url
		end
	end
	def destroy
		if logged_in? 
			message = "Successful Sign out!"
			flash[:success_logout] = message
			log_out
		else
			message = "You can't log out if you're not logged in!"
			flash[:warning] = message
		end

		log_out if logged_in?
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id 
	end

	#Remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

	#Returns the current logged-in user (if any)
	# def current_user
	# 	if session[:user_id]
	# 		@current_user ||= User.find_by(id: session[:user_id])
	# 	end
	# end

	# Returns true if the user is logged in, false otherwise.
	def logged_in?
		!current_user.nil?
	end

	# Logs out the current user.
	def log_out
		session.delete(:user_id)
		@current_user
	end

	#Forgets a persistent session
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	#Logs out the current user.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	#Redirects to stored location (or to the default).
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	#Stores the URL trying to be accessed.
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<div id='header-title'>
		<h2><%= link_to "trashtalk", root_path%></span>
	</div>
	<nav>
		<ul id='nav-links'>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<% if logged_in? %>			
				<li><%= link_to "New Post!", new_post_path %></li>
				<li><%= link_to "Sign Out", logout_path, method: "delete" %></li>
			<% else %>
				<li><%= link_to "Login", login_path %></li>
			<% end %>	
		</ul>
	</nav>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="page-content">
	<br>
	<h1>ALL THE POSTS!</h1>
	<br>
	<% @posts.each do |p| %>
		<h3><%= p.title %></h3>
		<div class="content-author-wrapper">
			<p><%= p.content %></p>
			
			<% if logged_in? %>
				<p>Written by - <%= User.find_by(id: p.author_id.to_s).name %> </p>
			<% end %>
		</div>
		<br>
	<% end %> 
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for(:post, url: posts_path, method: 'post') do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :content %>
	<%= f.text_area :content %>

	<%= f.submit "submit your post!" %>

<% end %>

app/views/static_pages/about.html.erb
<h1>about</h1>

app/views/static_pages/home.html.erb
<h1>Authentication and Posts part 1.0</h1>

app/views/users/index.html.erb
<h1>All the users</h1>
<% @users.each do |user| %>
	<p><%= user.id.to_s + ' ' + user.name %></p>
<% end %> 